version: '3.8'
services:
  connect:
    image: quay.io/debezium/connect:1.9
    container_name: debezium
    ports:
      - 8083:8083
    depends_on:
      - kafka
    links:
      - kafka
      - zookeeper
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  debezium-ui:
    image: debezium/debezium-ui:latest
    container_name: debezium-ui
    ports:
      - 8084:8080
    depends_on:
      - connect
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083
