global:
  scrape_interval: 2s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: mysql_exporter
    static_configs:
      - targets:
          - host.docker.internal:9104

  - job_name: kafka
    static_configs:
      - targets:
        - host.docker.internal:7071
